### ISSUE TITLE
Explicit matching of package name for installation

### ISSUE THREAD

**Issue by optiz0r** [mudler/luet#154]
For puppet provider, I am looking to be able to install exactly the package requested by the puppet catalog. This is tricky because `luet install` doesn't take an exact match, it takes a regex pattern. I need to be sure that when puppet specifies to install `cat/name` there's no way that `cat/name-foo` would be installed instead.

Currently I am working around this by wrapping the target in `^#{target}-[0-9].*$`. This obviously won't work for a package named like `cat/foo-1morething-1.2.3`.

It would be useful to have an option like `--exact` which forces luet into an exact string match without considering the input to be a pattern. An exact match should match both versioned and unversioned targets.

**Comment by mudler** [comment]
That's a generic issue we were already discussing with @geaaru , to me Luet has to be a bit more explict on package versions, so that's the upcoming change which is about to land in develop:

- `cat/name` -> will default to selecting any available
- `=cat/name` -> will default to gentoo parsing with regexp ( cc @geaaru  ) so also `=cat/name-1.1` works
- `cat/name@version` -> will select the specific version wanted, can also include ranges as `cat/name@>=1.1`
- `name` -> just name, category is empty

**Comment by optiz0r** [comment]
- `name` doesn't work as expected, e.g. `htop` does not match `sys-process/htop`.
- the `=` prefix appears to work as expected, I'll switch the puppet to using that instead of the regex anchors.

For comparison, with catgeory:
```
test ~ # luet install sys-process/htop
 Packages that are going to be installed in the system: 
  htop-sys-process-2.2.0+2 (mocaccino-portage-stable)
 By going forward, you are also accepting the licenses of the packages that you are going to install in your system.
 Do you want to continue with this operation? [y/N]: 
n
 Error: Aborted by user
```

And without:
```
test ~ # luet install htop
Error: Failed solving solution for package: Could not satisfy the constraints. Try again by removing deps 
```

The error message in this case appears to be erroneous also.

**Comment by optiz0r** [comment]
Also, `luet search` does not respect the `=` prefix, (I'm guessing uninstall does not either?)
All subcommands should handle package names consistently
